CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "age" int
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "description" varchar,
  "author" varchar,
  "content" varchar,
  "user_id" int,
  "tags_id" int
);

CREATE TABLE "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "comment" varchar,
  "user_id" int
);

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("tags_id") REFERENCES "tags" ("id");

insert into users (name, email, password, age) values
('Ian', 'ian@gmail.com', '1234', 32),
('Leonel', 'leonel@gmail.com', '9876', 24);

select * from users;

insert into comments (comment, user_id) values
('Primer Comentario', 1),
('Hola Mundo', 2),
('Probando la tabla comments', 1),
('Todo funciona correctamente', 2);

select * from comments;

insert into tags (name) values
('Tecnologia'),
('Cocina'),
('Espectaculos');

select * from tags;

insert into posts (title, description, author, content, user_id, tags_id) values
('Node Js', 'Aprendiendo base de datos', 'Leonel', '', 2, 1),
('Postgres', 'Creacion de base de datos', 'Ian', '', 1, 1);

select * from posts;